name: taxai
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

#--------------------PACKAGES--------------------#
dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2

# Utility Packages
http: ^1.1.0
intl: ^0.18.1
logger: ^2.0.1
url_launcher: ^6.1.12
flutter_native_splash: ^2.3.2
smooth_page_indicator: ^1.1.0

# Icons
iconsax: ^0.0.8
cupertino_icons: ^1.0.8

# state Management
get: ^4.7.2

# Product Specific

#--------------------PACKAGES END--------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

  


flutter:
  uses-material-design: true

  
  assets:
     - assets/logos/
     - assets/icons/
     - assets/images/onboarding/
    

  